NEG_LOGIC_OP = '!'
AND_LOGIC_OP = '&'
OR_LOGIC_OP = '|'
IF_THEN_LOGIC_OP = '>'
IFF_LOGIC_OP = '-'
EMPTY_LOGIC_OP = ""

LOGIC_OP_LIST = [NEG_LOGIC_OP, AND_LOGIC_OP, OR_LOGIC_OP, IF_THEN_LOGIC_OP, IFF_LOGIC_OP]

LEFT_PAREN = '('
RIGHT_PAREN = ')'
